import { useState, useEffect, useRef } from "react";
import QRCodeLib from "qrcode";
import { T, inputStyle, addBtnStyle, CURRENCIES, NumInput, Row, Result, MiniResult, Tip, CopyButton, CurrencyPicker } from "./theme";

export function RateCalc() {
  const [currency, setCurrency] = useState("USD");
  const sym = CURRENCIES.find(c => c.code === currency)?.symbol || "$";
  const [expenses, setExpenses] = useState(""); const [salary, setSalary] = useState(""); const [hours, setHours] = useState(""); const [buffer, setBuffer] = useState(20);
  const rate = (Number(expenses) > 0 || Number(salary) > 0) && Number(hours) > 0 ? ((Number(expenses) + Number(salary)) / Number(hours) * (1 + Number(buffer) / 100)).toFixed(2) : null;
  return <div><CurrencyPicker value={currency} onChange={setCurrency} /><Row label={`Monthly Expenses (${sym})`}><NumInput val={expenses} set={setExpenses} /></Row><Row label={`Desired Monthly Take-home (${sym})`}><NumInput val={salary} set={setSalary} /></Row><Row label="Billable Hours / Month"><NumInput val={hours} set={setHours} /></Row><Row label="Buffer / Profit (%)"><NumInput val={buffer} set={setBuffer} /></Row>{rate && <><Result label="Your Minimum Hourly Rate" value={`${sym}${rate}/hr`} /><CopyButton text={`My minimum hourly rate is ${sym}${rate}/hr — ToolForge`} /></>}<Tip>Going below this rate means you're losing money. Add 20–40% more for growth.</Tip></div>;
}

export function ProjectEstimator() {
  const [currency, setCurrency] = useState("USD");
  const sym = CURRENCIES.find(c => c.code === currency)?.symbol || "$";
  const nextId = useRef(3);
  const [tasks, setTasks] = useState([
    { id:1, name: "", hours: "" },
    { id:2, name: "", hours: "" },
  ]);
  const [rate, setRate]       = useState(75);
  const [buffer, setBuffer]   = useState(15);
  const [rush, setRush]       = useState(false);
  const [rushPct, setRushPct] = useState(25);

  const addTask = () => setTasks(ts => [...ts, { id: nextId.current++, name: "", hours: 0 }]);
  const delTask = id => setTasks(ts => ts.filter(t => t.id !== id));
  const updateTask = (id, field, val) => setTasks(ts => ts.map(t => t.id === id ? { ...t, [field]: val } : t));

  const totalHours   = tasks.reduce((s, t) => s + Number(t.hours || 0), 0);
  const basePrice    = totalHours * Number(rate);
  const withBuffer   = basePrice * (1 + Number(buffer) / 100);
  const finalPrice   = rush ? withBuffer * (1 + Number(rushPct) / 100) : withBuffer;
  const priceStr     = Number(finalPrice.toFixed(0)).toLocaleString();

  const delBtn = { background:"none", border:`1px solid ${T.border}`, borderRadius:8, width:30, height:36, cursor:"pointer", fontSize:14, color:T.muted, flexShrink:0, display:"flex", alignItems:"center", justifyContent:"center" };


  const taskLines = tasks.filter(t => t.name).map(t =>
    t.name + ": " + t.hours + "h x " + sym + rate + "/h = " + sym + Number((Number(t.hours) * Number(rate)).toFixed(0)).toLocaleString()
  ).join("\n");
  const rushLine = rush ? "\nRush fee (" + rushPct + "%): " + sym + Number((finalPrice - withBuffer).toFixed(0)).toLocaleString() : "";
  const quoteText = [
    "Project Quote",
    "─────────────────",
    taskLines,
    "─────────────────",
    "Subtotal:  " + sym + Number(basePrice.toFixed(0)).toLocaleString(),
    "Buffer (" + buffer + "%): " + sym + Number((withBuffer - basePrice).toFixed(0)).toLocaleString() + rushLine,
    "─────────────────",
    "TOTAL:     " + sym + priceStr,
    "─────────────────",
    "Estimated: " + totalHours + " hours",
    "Generated by ToolForge",
  ].join("\n");


  return (
    <div>
      <CurrencyPicker value={currency} onChange={setCurrency} />

      {/* Column headers */}
      <div style={{ display:"flex", gap:8, marginBottom:4, paddingRight:38 }}>
        <div style={{ flex:1, fontSize:10, color:T.muted, fontFamily:"Syne, sans-serif", fontWeight:700, paddingLeft:2 }}>TASK</div>
        <div style={{ width:72, fontSize:10, color:T.muted, fontFamily:"Syne, sans-serif", fontWeight:700 }}>HOURS</div>
      </div>

      {/* Task rows */}
      {tasks.map(t => (
        <div key={t.id} style={{ display:"flex", gap:8, marginBottom:8, alignItems:"center" }}>
          <input value={t.name} onChange={e => updateTask(t.id, "name", e.target.value)}
            style={{ ...inputStyle, flex:1 }} placeholder="e.g. Homepage design" />
          <input type="number" value={t.hours} min={0}
            onChange={e => updateTask(t.id, "hours", e.target.value)}
            style={{ ...inputStyle, width:72, textAlign:"center" }} placeholder="0" />
          <button onClick={() => delTask(t.id)} style={delBtn} title="Remove">✕</button>
        </div>
      ))}
      <button onClick={addTask} style={addBtnStyle}>+ Add Task</button>

      {/* Rate + buffer */}
      <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:10, marginTop:4 }}>
        <Row label={`Hourly Rate (${sym})`}><NumInput val={rate} set={setRate} /></Row>
        <Row label="Revision Buffer (%)"><NumInput val={buffer} set={setBuffer} /></Row>
      </div>

      {/* Rush fee toggle */}
      <div style={{ marginTop:8, padding:"11px 14px", borderRadius:12, border:`1px solid ${rush ? T.accent : T.border}`, background:rush ? T.accentDim : T.card, transition:"all 0.2s" }}>
        <div style={{ display:"flex", alignItems:"center", justifyContent:"space-between", marginBottom: rush ? 10 : 0 }}>
          <div>
            <div style={{ fontFamily:"Syne, sans-serif", fontWeight:700, fontSize:12, color: rush ? T.accent : T.ink }}>⚡ Rush Fee</div>
            <div style={{ fontSize:10, color:T.muted, marginTop:1, fontFamily:"DM Sans, sans-serif" }}>Client needs it fast? Add a surcharge.</div>
          </div>
          <div onClick={() => setRush(r => !r)}
            style={{ width:40, height:22, borderRadius:11, background: rush ? T.accent : T.border, position:"relative", cursor:"pointer", transition:"background 0.2s", flexShrink:0 }}>
            <div style={{ position:"absolute", top:3, left: rush ? 21 : 3, width:16, height:16, borderRadius:"50%", background:"white", transition:"left 0.2s", boxShadow:"0 1px 3px rgba(0,0,0,0.2)" }} />
          </div>
        </div>
        {rush && (
          <Row label="Rush Surcharge (%)"><NumInput val={rushPct} set={setRushPct} /></Row>
        )}
      </div>

      {/* Price breakdown */}
      {totalHours > 0 && (
        <div style={{ marginTop:14, padding:"16px 18px", borderRadius:14, background:T.card, border:`2px solid ${T.accent}22` }}>
          <div style={{ fontFamily:"Syne, sans-serif", fontWeight:700, fontSize:11, color:T.muted, marginBottom:10, letterSpacing:0.5 }}>PRICE BREAKDOWN</div>
          <div style={{ display:"flex", flexDirection:"column", gap:6, marginBottom:12 }}>
            <div style={{ display:"flex", justifyContent:"space-between", fontSize:12, color:T.muted, fontFamily:"DM Sans, sans-serif" }}>
              <span>{totalHours}h × {sym}{Number(rate).toLocaleString()}/h</span>
              <span>{sym}{Number(basePrice.toFixed(0)).toLocaleString()}</span>
            </div>
            <div style={{ display:"flex", justifyContent:"space-between", fontSize:12, color:T.muted, fontFamily:"DM Sans, sans-serif" }}>
              <span>Buffer ({buffer}%)</span>
              <span>+ {sym}{Number((withBuffer - basePrice).toFixed(0)).toLocaleString()}</span>
            </div>
            {rush && (
              <div style={{ display:"flex", justifyContent:"space-between", fontSize:12, color:T.accent, fontFamily:"DM Sans, sans-serif" }}>
                <span>Rush fee ({rushPct}%)</span>
                <span>+ {sym}{Number((finalPrice - withBuffer).toFixed(0)).toLocaleString()}</span>
              </div>
            )}
            <div style={{ borderTop:`1px solid ${T.border}`, paddingTop:8, display:"flex", justifyContent:"space-between", alignItems:"baseline" }}>
              <span style={{ fontFamily:"Syne, sans-serif", fontWeight:700, fontSize:13, color:T.ink }}>Total</span>
              <span style={{ fontFamily:"Syne, sans-serif", fontWeight:800, fontSize:28, color:T.accent }}>{sym}{priceStr}</span>
            </div>
          </div>
        </div>
      )}

      <div style={{ marginTop:10 }}>
        <CopyButton text={quoteText} label="📋 Copy Full Quote" />
      </div>
    </div>
  );
}

export function GPACalc() {
  const GRADES = [["A+",4.3],["A",4.0],["A-",3.7],["B+",3.3],["B",3.0],["B-",2.7],["C+",2.3],["C",2.0],["C-",1.7],["D+",1.3],["D",1.0],["D-",0.7],["F",0]];
  const toPoints = g => GRADES.find(x => x[0] === g)?.[1] ?? 0;

  const [courses, setCourses] = useState([
    { id:1, name: "", grade: "A", credits: 3 },
    { id:2, name: "", grade: "B+", credits: 3 },
  ]);
  const [showTarget, setShowTarget] = useState(false);
  const [targetGPA, setTargetGPA]   = useState("3.5");
  const [newCredits, setNewCredits] = useState(3);
  const nextId = useRef(3);

  const addCourse   = () => { setCourses(cs => [...cs, { id: nextId.current++, name: "", grade: "B", credits: 3 }]); };
  const delCourse   = id  => setCourses(cs => cs.filter(c => c.id !== id));
  const updateField = (id, field, val) => setCourses(cs => cs.map(c => c.id === id ? { ...c, [field]: val } : c));

  const totalCredits  = courses.reduce((s, c) => s + Number(c.credits || 0), 0);
  const totalPoints   = courses.reduce((s, c) => s + toPoints(c.grade) * Number(c.credits || 0), 0);
  const gpa           = totalCredits ? (totalPoints / totalCredits).toFixed(2) : "0.00";
  const gpaNum        = parseFloat(gpa);
  const gpaColor      = gpaNum >= 3.7 ? T.green : gpaNum >= 3.0 ? T.blue : gpaNum >= 2.0 ? T.accent : "#dc2626";
  const gpaLabel      = gpaNum >= 3.7 ? "Dean's List 🎓" : gpaNum >= 3.0 ? "Good Standing ✓" : gpaNum >= 2.0 ? "Satisfactory" : "At Risk ⚠️";

  // "What grade do I need?" calculator
  const tgt = parseFloat(targetGPA) || 0;
  const nc  = Number(newCredits) || 0;
  const neededPoints = tgt * (totalCredits + nc) - totalPoints;
  const neededPPU    = nc > 0 ? neededPoints / nc : null;
  const neededGrade  = neededPPU === null ? null
    : neededPPU <= 0   ? "Any grade works! 🎉"
    : neededPPU > 4.3  ? "Not achievable this semester"
    : GRADES.slice().reverse().find(g => g[1] >= neededPPU)?.[0] ?? "A+";

  const rowStyle = { display:"flex", gap:8, marginBottom:8, alignItems:"center" };
  const delBtn   = { background:"none", border:`1px solid ${T.border}`, borderRadius:8, width:30, height:36, cursor:"pointer", fontSize:14, color:T.muted, flexShrink:0, display:"flex", alignItems:"center", justifyContent:"center" };

  return (
    <div>
      {/* Course column headers */}
      <div style={{ display:"flex", gap:8, marginBottom:4, paddingRight:38 }}>
        <div style={{ flex:1, fontSize:10, color:T.muted, fontFamily:"Syne, sans-serif", fontWeight:700, paddingLeft:2 }}>COURSE (OPTIONAL)</div>
        <div style={{ width:80, fontSize:10, color:T.muted, fontFamily:"Syne, sans-serif", fontWeight:700 }}>GRADE</div>
        <div style={{ width:60, fontSize:10, color:T.muted, fontFamily:"Syne, sans-serif", fontWeight:700 }}>CREDITS</div>
      </div>

      {/* Course rows */}
      {courses.map(c => (
        <div key={c.id} style={rowStyle}>
          <input value={c.name} onChange={e => updateField(c.id, "name", e.target.value)}
            style={{ ...inputStyle, flex:1 }} placeholder="e.g. Math 101" />
          <select value={c.grade} onChange={e => updateField(c.id, "grade", e.target.value)}
            style={{ ...inputStyle, width:80, paddingLeft:8 }}>
            {GRADES.map(g => <option key={g[0]}>{g[0]}</option>)}
          </select>
          <input type="number" value={c.credits} min={0} max={12}
            onChange={e => updateField(c.id, "credits", e.target.value)}
            style={{ ...inputStyle, width:60, textAlign:"center" }} placeholder="3" />
          <button onClick={() => delCourse(c.id)} style={delBtn} title="Remove">✕</button>
        </div>
      ))}

      <button onClick={addCourse} style={addBtnStyle}>+ Add Course</button>

      {/* GPA result */}
      {totalCredits > 0 && (
        <div style={{ marginTop:16, padding:"16px 18px", borderRadius:14, background:T.card, border:`2px solid ${gpaColor}22` }}>
          <div style={{ display:"flex", alignItems:"baseline", justifyContent:"space-between", marginBottom:4 }}>
            <div style={{ fontFamily:"Syne, sans-serif", fontWeight:700, fontSize:13, color:T.muted }}>YOUR GPA</div>
            <div style={{ fontSize:11, color:gpaColor, fontFamily:"Syne, sans-serif", fontWeight:700 }}>{gpaLabel}</div>
          </div>
          <div style={{ fontFamily:"Syne, sans-serif", fontWeight:800, fontSize:42, color:gpaColor, lineHeight:1 }}>{gpa}</div>
          <div style={{ fontSize:11, color:T.muted, marginTop:6, fontFamily:"DM Sans, sans-serif" }}>{totalCredits} credit hours · {courses.length} course{courses.length !== 1 ? "s" : ""}</div>
        </div>
      )}

      {/* What grade do I need? */}
      <div style={{ marginTop:12, borderRadius:12, border:`1px solid ${T.border}`, overflow:"hidden" }}>
        <div onClick={() => setShowTarget(t => !t)}
          style={{ padding:"11px 14px", display:"flex", alignItems:"center", justifyContent:"space-between", cursor:"pointer", background:showTarget ? T.purpleDim : T.card }}>
          <div style={{ fontFamily:"Syne, sans-serif", fontWeight:700, fontSize:12, color:T.purple }}>🎯 What grade do I need?</div>
          <span style={{ fontSize:13, color:T.muted, transform:showTarget?"rotate(180deg)":"rotate(0deg)", transition:"transform 0.2s", display:"inline-block" }}>▾</span>
        </div>
        {showTarget && (
          <div style={{ padding:"14px 14px 16px", background:T.card, borderTop:`1px solid ${T.border}` }}>
            <div style={{ fontSize:12, color:T.muted, marginBottom:12, fontFamily:"DM Sans, sans-serif", lineHeight:1.5 }}>
              Enter your target GPA and how many credits your next course is worth — we'll tell you what grade you need.
            </div>
            <div style={{ display:"flex", gap:10, marginBottom:12 }}>
              <div style={{ flex:1 }}>
                <div style={{ fontSize:10, color:T.muted, fontFamily:"Syne, sans-serif", fontWeight:700, marginBottom:4 }}>TARGET GPA</div>
                <input type="number" value={targetGPA} min="0" max="4.3" step="0.1"
                  onChange={e => setTargetGPA(e.target.value)}
                  style={{ ...inputStyle, textAlign:"center" }} placeholder="e.g. 3.5" />
              </div>
              <div style={{ flex:1 }}>
                <div style={{ fontSize:10, color:T.muted, fontFamily:"Syne, sans-serif", fontWeight:700, marginBottom:4 }}>NEXT COURSE CREDITS</div>
                <input type="number" value={newCredits} min={1} max={12}
                  onChange={e => setNewCredits(e.target.value)}
                  style={{ ...inputStyle, textAlign:"center" }} placeholder="3" />
              </div>
            </div>
            {neededGrade && totalCredits > 0 && (
              <div style={{ padding:"12px 14px", borderRadius:10, background:T.purpleDim, border:`1px solid ${T.purple}33`, textAlign:"center" }}>
                <div style={{ fontSize:11, color:T.purple, fontFamily:"DM Sans, sans-serif", marginBottom:4 }}>You need at least</div>
                <div style={{ fontFamily:"Syne, sans-serif", fontWeight:800, fontSize:32, color:T.purple, lineHeight:1 }}>
                  {neededGrade.length <= 2 ? neededGrade : neededGrade}
                </div>
                {neededGrade.length <= 2 && (
                  <div style={{ fontSize:11, color:T.purple, opacity:0.8, marginTop:4, fontFamily:"DM Sans, sans-serif" }}>
                    in your next {newCredits}-credit course
                  </div>
                )}
              </div>
            )}
            {totalCredits === 0 && (
              <div style={{ fontSize:12, color:T.muted, textAlign:"center", padding:"8px 0", fontFamily:"DM Sans, sans-serif" }}>Add at least one course above first</div>
            )}
          </div>
        )}
      </div>

      <div style={{ marginTop:10 }}>
        <CopyButton text={`My GPA is ${gpa} (${totalCredits} credit hours) — calculated on ToolForge`} />
      </div>
    </div>
  );
}

export function TipSplitter() {
  const [currency, setCurrency] = useState("USD");
  const sym = CURRENCIES.find(c => c.code === currency)?.symbol || "$";
  const [bill, setBill]     = useState("");
  const [tip, setTip]       = useState(18);
  const [customTip, setCustomTip] = useState("");
  const [useCustom, setUseCustom] = useState(false);
  const [people, setPeople] = useState(2);

  const activeTip   = useCustom ? (parseFloat(customTip) || 0) : tip;
  const billNum     = parseFloat(bill) || 0;
  const tipAmt      = (billNum * activeTip / 100).toFixed(2);
  const total       = (billNum + parseFloat(tipAmt)).toFixed(2);
  const perPerson   = people > 0 ? (parseFloat(total) / people).toFixed(2) : "0.00";
  const hasResult   = billNum > 0;

  return (
    <div>
      <CurrencyPicker value={currency} onChange={setCurrency} />
      <Row label={`Bill Total (${sym})`}><NumInput val={bill} set={setBill} /></Row>

      <Row label="Tip">
        <div style={{ display:"flex", gap:6, flexWrap:"wrap" }}>
          {[10,15,18,20,25].map(p => (
            <button key={p} onClick={() => { setTip(p); setUseCustom(false); }}
              style={{ flex:1, minWidth:40, padding:"6px 0", borderRadius:8, border:`1px solid ${!useCustom&&tip===p?T.accent:T.border}`, background:!useCustom&&tip===p?T.accentDim:T.card, cursor:"pointer", fontSize:12, fontFamily:"DM Sans, sans-serif", color:!useCustom&&tip===p?T.accent:T.muted }}>
              {p}%
            </button>
          ))}
          <input
            type="number" placeholder="Custom" value={customTip}
            onChange={e => { setCustomTip(e.target.value); setUseCustom(true); }}
            onFocus={() => setUseCustom(true)}
            style={{ ...inputStyle, flex:1, minWidth:60, padding:"6px 8px", border:`1px solid ${useCustom?T.accent:T.border}`, background:useCustom?T.accentDim:T.card, color:useCustom?T.accent:T.ink, textAlign:"center" }}
          />
        </div>
      </Row>

      <Row label="Number of People"><NumInput val={people} set={setPeople} /></Row>

      {hasResult && (
        <>
          <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:10, marginTop:12 }}>
            <MiniResult label={"Tip (" + activeTip + "%)"} value={sym + tipAmt} />
            <MiniResult label="Total Bill" value={sym + total} />
          </div>
          <Result label="Each Person Pays" value={sym + perPerson} />
          <CopyButton text={"Bill split: " + sym + perPerson + " each (" + activeTip + "% tip) — ToolForge"} />
        </>
      )}
    </div>
  );
}

export function MarginCalc() {
  const [currency, setCurrency] = useState("USD");
  const sym = CURRENCIES.find(c => c.code === currency)?.symbol || "$";
  const [cost, setCost]     = useState("");
  const [price, setPrice]   = useState("");
  const [targetMargin, setTargetMargin] = useState("40");
  const [showReverse, setShowReverse]   = useState(false);

  const costNum  = parseFloat(cost)  || 0;
  const priceNum = parseFloat(price) || 0;
  const hasResult = costNum > 0 && priceNum > 0;

  const profit = hasResult ? (priceNum - costNum).toFixed(2) : "0.00";
  const margin = hasResult && priceNum > 0 ? ((parseFloat(profit) / priceNum) * 100).toFixed(1) : 0;
  const markup = hasResult && costNum > 0  ? (((priceNum - costNum) / costNum) * 100).toFixed(1) : 0;
  const marginColor = margin >= 40 ? T.green : margin >= 20 ? T.accent : "#dc2626";

  // Reverse: what price gives target margin?
  const tgt = parseFloat(targetMargin) || 0;
  const neededPrice = costNum > 0 && tgt < 100 ? (costNum / (1 - tgt / 100)).toFixed(2) : null;

  return (
    <div>
      <CurrencyPicker value={currency} onChange={setCurrency} />
      <Row label={`Cost Price (${sym})`}><NumInput val={cost} set={setCost} /></Row>
      <Row label={`Selling Price (${sym})`}><NumInput val={price} set={setPrice} /></Row>

      {hasResult && (
        <>
          <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:10, marginTop:12 }}>
            <MiniResult label="Profit" value={sym + profit} />
            <MiniResult label="Markup %" value={markup + "%"} />
          </div>
          <Result label="Profit Margin" value={margin + "%"} color={marginColor} />
          <CopyButton text={"Profit margin: " + margin + "% — ToolForge"} />
          <Tip>{margin >= 40 ? "Excellent margin!" : margin >= 20 ? "Decent margin." : "Low margin — review your pricing."}</Tip>
        </>
      )}

      {/* Reverse calculator */}
      <div style={{ marginTop:12, borderRadius:12, border:`1px solid ${T.border}`, overflow:"hidden" }}>
        <div onClick={() => setShowReverse(r => !r)}
          style={{ padding:"11px 14px", display:"flex", alignItems:"center", justifyContent:"space-between", cursor:"pointer", background:showReverse?T.greenDim:T.card }}>
          <div style={{ fontFamily:"Syne, sans-serif", fontWeight:700, fontSize:12, color:T.green }}>🎯 What price hits my target margin?</div>
          <span style={{ fontSize:13, color:T.muted, transform:showReverse?"rotate(180deg)":"rotate(0deg)", transition:"transform 0.2s", display:"inline-block" }}>▾</span>
        </div>
        {showReverse && (
          <div style={{ padding:"14px", background:T.card, borderTop:`1px solid ${T.border}` }}>
            <Row label="Target Margin (%)"><NumInput val={targetMargin} set={setTargetMargin} /></Row>
            {neededPrice ? (
              <div style={{ padding:"12px 14px", borderRadius:10, background:T.greenDim, border:`1px solid ${T.green}33`, textAlign:"center", marginTop:8 }}>
                <div style={{ fontSize:11, color:T.green, fontFamily:"DM Sans, sans-serif", marginBottom:4 }}>Sell at</div>
                <div style={{ fontFamily:"Syne, sans-serif", fontWeight:800, fontSize:32, color:T.green, lineHeight:1 }}>{sym}{neededPrice}</div>
                <div style={{ fontSize:11, color:T.green, opacity:0.8, marginTop:4, fontFamily:"DM Sans, sans-serif" }}>to achieve {targetMargin}% margin</div>
              </div>
            ) : (
              <div style={{ fontSize:12, color:T.muted, textAlign:"center", padding:"8px 0", fontFamily:"DM Sans, sans-serif" }}>Enter a cost price above first</div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

export function BreakEvenCalc() {
  const [currency, setCurrency] = useState("USD");
  const sym = CURRENCIES.find(c => c.code === currency)?.symbol || "$";
  const [fixed, setFixed]       = useState("");
  const [varCost, setVarCost]   = useState("");
  const [sellPrice, setSellPrice] = useState("");
  const [actualUnits, setActualUnits] = useState("");

  const fixedNum = parseFloat(fixed) || 0;
  const varNum   = parseFloat(varCost) || 0;
  const sellNum  = parseFloat(sellPrice) || 0;
  const contrib  = sellNum - varNum;
  const hasResult = fixedNum > 0 && contrib > 0;

  const units   = hasResult ? Math.ceil(fixedNum / contrib) : null;
  const revenue = units ? (units * sellNum).toFixed(0) : null;

  // Profit at actual units sold
  const actualNum   = parseInt(actualUnits) || 0;
  const actualProfit = actualNum > 0 && hasResult
    ? ((actualNum - units) * contrib).toFixed(0)
    : null;

  return (
    <div>
      <CurrencyPicker value={currency} onChange={setCurrency} />
      <Row label={`Monthly Fixed Costs (${sym})`}><NumInput val={fixed} set={setFixed} /></Row>
      <Row label={`Variable Cost per Unit (${sym})`}><NumInput val={varCost} set={setVarCost} /></Row>
      <Row label={`Selling Price per Unit (${sym})`}><NumInput val={sellPrice} set={setSellPrice} /></Row>

      {hasResult && (
        <>
          <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:10, marginTop:12 }}>
            <MiniResult label="Contribution Margin" value={sym + contrib.toFixed(2)} />
            <MiniResult label="Break-Even Revenue" value={sym + Number(revenue).toLocaleString()} />
          </div>
          <Result label="Units to Break Even" value={units.toLocaleString()} />
          <CopyButton text={"Break-even: " + units + " units at " + sym + sellNum + "/unit — ToolForge"} />
          <Tip>{"Sell more than " + units + " units/month and you're profitable."}</Tip>

          {/* Profit checker */}
          <div style={{ marginTop:12, padding:"12px 14px", borderRadius:12, border:`1px solid ${T.border}`, background:T.card }}>
            <div style={{ fontFamily:"Syne, sans-serif", fontWeight:700, fontSize:12, color:T.ink, marginBottom:8 }}>📊 How profitable am I at X units?</div>
            <Row label="Units You Expect to Sell"><NumInput val={actualUnits} set={setActualUnits} /></Row>
            {actualProfit !== null && (
              <div style={{ marginTop:8, padding:"10px 14px", borderRadius:10, background: parseFloat(actualProfit) >= 0 ? T.greenDim : "#fef2f2", border:`1px solid ${parseFloat(actualProfit) >= 0 ? T.green : "#fecaca"}`, textAlign:"center" }}>
                <div style={{ fontFamily:"Syne, sans-serif", fontWeight:800, fontSize:26, color: parseFloat(actualProfit) >= 0 ? T.green : "#dc2626" }}>
                  {parseFloat(actualProfit) >= 0 ? "+" : ""}{sym}{Math.abs(parseFloat(actualProfit)).toLocaleString()}
                </div>
                <div style={{ fontSize:11, color: parseFloat(actualProfit) >= 0 ? T.green : "#dc2626", fontFamily:"DM Sans, sans-serif", marginTop:3 }}>
                  {parseFloat(actualProfit) >= 0
                    ? "profit — " + (actualNum - units) + " units above break-even"
                    : "loss — " + (units - actualNum) + " units below break-even"}
                </div>
              </div>
            )}
          </div>
        </>
      )}
    </div>
  );
}

export function DeadlineCountdown({ label, setLabel, target, setTarget, pinned, onTogglePin, running, onStart, onStop }) {
  const getDiff = () => new Date(target) - new Date();
  const fmt = () => { const diff = getDiff(); if (diff <= 0) return "Past due!"; const d = Math.floor(diff/864e5); const h = Math.floor((diff%864e5)/36e5); const m = Math.floor((diff%36e5)/6e4); return `${d}d ${h}h ${m}m`; };
  const diff = getDiff();
  const days = diff > 0 ? Math.floor(diff/864e5) : 0;
  const hours = diff > 0 ? Math.floor((diff%864e5)/36e5) : 0;
  const mins = diff > 0 ? Math.floor((diff%36e5)/6e4) : 0;
  return (
    <div>
      <Row label="Event / Deadline Name"><input value={label} onChange={e => setLabel(e.target.value)} style={inputStyle} /></Row>
      <Row label="Target Date"><input type="date" value={target} onChange={e => setTarget(e.target.value)} style={inputStyle} /></Row>
      {diff <= 0 ? <Result label={label} value="Past due!" color="#dc2626" /> : <>
        {running && (
          <div style={{ marginBottom: 12, padding: "12px 14px", background: T.purpleDim, borderRadius: 10, border: `1px solid ${T.purple}44` }}>
            <div style={{ fontSize: 10, color: T.purple, fontFamily: "Syne, sans-serif", fontWeight: 700, marginBottom: 2 }}>COUNTING DOWN</div>
            <div style={{ fontSize: 24, fontWeight: 800, color: T.purple, fontFamily: "Syne, sans-serif" }}>{fmt()}</div>
          </div>
        )}
        {!running && <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 8, marginTop: 12 }}><MiniResult label="Days" value={days} /><MiniResult label="Hours" value={hours} /><MiniResult label="Minutes" value={mins} /></div>}
        <CopyButton text={`${days} days until ${label} — ToolForge`} />
        <div style={{ display: "flex", gap: 8, marginTop: 8 }}>
          <button onClick={running ? onStop : onStart} style={{ flex: 1, padding: "9px 0", borderRadius: 9, border: "none", background: running ? "#fee2e2" : T.purple, color: running ? "#dc2626" : "white", fontSize: 12, fontFamily: "Syne, sans-serif", fontWeight: 700, cursor: "pointer" }}>
            {running ? "⏹ Stop" : "▶ Start Countdown"}
          </button>
          <button onClick={onTogglePin} style={{ flex: 1, padding: "9px 0", borderRadius: 9, border: `1.5px solid ${pinned ? T.purple : T.border}`, background: pinned ? T.purple : "white", color: pinned ? "white" : T.muted, fontSize: 12, fontFamily: "Syne, sans-serif", fontWeight: 700, cursor: "pointer" }}>
            {pinned ? "📌 Pinned" : "📌 Pin"}
          </button>
        </div>
      </>}
    </div>
  );
}

export function PomodoroTimer({ modes, modeId, secondsLeft, running, pinned, sessions, paused, onStart, onPause, onReset, onSwitchMode, onTogglePin }) {
  const mode = modes.find(m => m.id === modeId);
  const fmt = (s) => `${String(Math.floor(s / 60)).padStart(2, "0")}:${String(s % 60).padStart(2, "0")}`;
  const total = mode.mins * 60;
  const progress = 1 - secondsLeft / total;
  const circumference = 2 * Math.PI * 54;
  return (
    <div style={{ maxWidth: 360, margin: "0 auto" }}>
      <div style={{ display: "flex", gap: 6, marginBottom: 24 }}>
        {modes.map(m => (
          <button key={m.id} onClick={() => onSwitchMode(m.id)} style={{ flex: 1, padding: "8px 0", borderRadius: 10, border: `1.5px solid ${modeId === m.id ? m.color : T.border}`, background: modeId === m.id ? m.colorDim : "white", color: modeId === m.id ? m.color : T.muted, fontSize: 11, fontFamily: "Syne, sans-serif", fontWeight: 700, cursor: "pointer", transition: "all 0.15s" }}>
            {m.icon} {m.label}
          </button>
        ))}
      </div>
      <div style={{ display: "flex", flexDirection: "column", alignItems: "center", marginBottom: 24 }}>
        <div style={{ position: "relative", width: 140, height: 140 }}>
          <svg width="140" height="140" style={{ transform: "rotate(-90deg)" }}>
            <circle cx="70" cy="70" r="54" fill="none" stroke={T.border} strokeWidth="8" />
            <circle cx="70" cy="70" r="54" fill="none" stroke={mode.color} strokeWidth="8" strokeDasharray={circumference} strokeDashoffset={circumference * (1 - progress)} strokeLinecap="round" style={{ transition: "stroke-dashoffset 0.8s ease" }} />
          </svg>
          <div style={{ position: "absolute", inset: 0, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
            <div style={{ fontSize: 32, fontWeight: 800, fontFamily: "Syne, sans-serif", color: mode.color, lineHeight: 1 }}>{fmt(secondsLeft)}</div>
            <div style={{ fontSize: 11, color: T.muted, marginTop: 4, fontFamily: "DM Sans, sans-serif" }}>{mode.label}</div>
          </div>
        </div>
        {sessions > 0 && <div style={{ marginTop: 10, display: "flex", gap: 4 }}>{Array.from({ length: sessions }).map((_, i) => <span key={i} style={{ fontSize: 14 }}>🍅</span>)}</div>}
      </div>
      <div style={{ display: "flex", gap: 10, marginBottom: 10 }}>
        {!running ? (
          <button onClick={onStart} style={{ flex: 1, padding: "13px 0", background: mode.color, color: "white", border: "none", borderRadius: 12, fontSize: 15, fontWeight: 800, fontFamily: "Syne, sans-serif", cursor: "pointer" }}>
            {paused ? "▶ Resume" : "▶ Start"}
          </button>
        ) : (
          <button onClick={onPause} style={{ flex: 1, padding: "13px 0", background: mode.colorDim, color: mode.color, border: `2px solid ${mode.color}`, borderRadius: 12, fontSize: 15, fontWeight: 800, fontFamily: "Syne, sans-serif", cursor: "pointer" }}>⏸ Pause</button>
        )}
        <button onClick={onReset} style={{ padding: "13px 18px", background: "white", color: T.muted, border: `1.5px solid ${T.border}`, borderRadius: 12, fontSize: 13, fontFamily: "DM Sans, sans-serif", cursor: "pointer" }}>↺ Reset</button>
        <button onClick={onTogglePin} style={{ padding: "13px 14px", background: pinned ? mode.colorDim : "white", color: pinned ? mode.color : T.muted, border: `1.5px solid ${pinned ? mode.color : T.border}`, borderRadius: 12, fontSize: 13, fontFamily: "Syne, sans-serif", fontWeight: 700, cursor: "pointer" }}>📌</button>
      </div>
      {running && <div style={{ padding: "9px 12px", borderRadius: 9, background: mode.colorDim, border: `1px solid ${mode.color}33`, fontSize: 12, color: mode.color, fontFamily: "DM Sans, sans-serif", textAlign: "center" }}>← Go back — timer keeps running in the widget</div>}
    </div>
  );
}

export function FloatingWidget({ widgets, removeWidget, activePill, setActivePill, onOpenTool }) {
  const [expanded, setExpanded] = useState(true);
  const [, forceUpdate] = useState(0);
  const tickRef = useRef(null);
  const keys = Object.keys(widgets);

  useEffect(() => {
    tickRef.current = setInterval(() => forceUpdate(n => n + 1), 1000);
    return () => clearInterval(tickRef.current);
  }, []);

  useEffect(() => {
    if (keys.length > 0 && (!activePill || !widgets[activePill])) setActivePill(keys[0]);
  }, [widgets]);

  if (keys.length === 0) return null;

  const getDisplay = (w) => {
    if (w.type === "pomodoro") {
      const s = w.secondsLeft || 0;
      return (w.paused ? "⏸ " : "") + String(Math.floor(s/60)).padStart(2,"0") + ":" + String(s%60).padStart(2,"0");
    }
    if (w.type === "deadline") {
      const diff = new Date(w.targetDate) - new Date();
      if (diff <= 0) return "Past due!";
      return `${Math.floor(diff/864e5)}d ${Math.floor((diff%864e5)/36e5)}h ${Math.floor((diff%36e5)/6e4)}m`;
    }
    return "";
  };

  const active = widgets[activePill] || widgets[keys[0]];
  const activeId = widgets[activePill] ? activePill : keys[0];

  return (
    <div className="tf-floating-widget" style={{ position: "fixed", bottom: 16, left: "50%", transform: "translateX(-50%)", zIndex: 200, maxWidth: 440, width: "calc(100% - 32px)", background: "white", borderRadius: 16, border: `1px solid ${T.border}`, boxShadow: "0 8px 32px rgba(0,0,0,0.12)", padding: "10px 12px" }}>
      <div style={{ display: "flex", gap: 6, alignItems: "center" }}>
        {keys.map(id => {
          const w = widgets[id];
          const isActive = id === activeId;
          const display = getDisplay(w);
          return (
            <div key={id} onClick={() => { setActivePill(id); onOpenTool(id); }}
              style={{ display: "flex", alignItems: "center", gap: 6, padding: "7px 12px", borderRadius: 99, cursor: "pointer", border: `1.5px solid ${isActive ? w.color : T.border}`, background: isActive ? w.colorDim : T.bg, flex: isActive ? 1 : "0 0 auto", transition: "all 0.2s", minWidth: 0 }}>
              <span style={{ fontSize: 16, flexShrink: 0 }}>{w.icon}</span>
              {isActive && <div style={{ display: "flex", flexDirection: "column", minWidth: 0 }}>
                <div style={{ fontSize: 10, color: w.color, fontFamily: "DM Sans, sans-serif", opacity: 0.8, whiteSpace: "nowrap" }}>{w.sessionLabel || w.label || "Active"}</div>
                <div style={{ fontSize: 15, fontWeight: 800, color: w.color, fontFamily: "Syne, sans-serif", whiteSpace: "nowrap" }}>{display}</div>
              </div>}
              {!isActive && <div style={{ fontSize: 12, fontWeight: 700, color: T.muted, fontFamily: "Syne, sans-serif", whiteSpace: "nowrap" }}>{display}</div>}
            </div>
          );
        })}
        <div style={{ marginLeft: "auto", display: "flex", gap: 4, flexShrink: 0 }}>
          {keys.length > 1 && (
            <button onClick={() => setExpanded(e => !e)} style={{ background: "none", border: "none", fontSize: 11, color: T.muted, cursor: "pointer", fontFamily: "DM Sans, sans-serif", padding: "4px 6px", borderRadius: 6, whiteSpace: "nowrap" }}>
              {expanded ? "less ▴" : `+${keys.length - 1} more ▾`}
            </button>
          )}
          <button onClick={() => { keys.forEach(id => removeWidget(id)); }} style={{ background: T.bg, border: "none", borderRadius: 8, color: T.muted, fontSize: 13, width: 26, height: 26, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center" }}>✕</button>
        </div>
      </div>
      {keys.length > 1 && expanded && (
        <div style={{ marginTop: 10, paddingTop: 10, borderTop: `1px solid ${T.border}` }}>
          {keys.map(id => {
            const w = widgets[id];
            return (
              <div key={id} style={{ display: "flex", alignItems: "center", gap: 8, padding: "6px 0" }}>
                <span style={{ fontSize: 14 }}>{w.icon}</span>
                <div style={{ flex: 1, fontFamily: "Syne, sans-serif", fontWeight: 700, fontSize: 12, color: w.color }}>{w.sessionLabel || w.label || w.toolId}</div>
                <div style={{ fontFamily: "Syne, sans-serif", fontWeight: 800, fontSize: 14, color: w.color }}>{getDisplay(w)}</div>
                <button onClick={() => removeWidget(id)} style={{ background: "none", border: "none", cursor: "pointer", color: T.muted, fontSize: 13, padding: "0 4px" }}>✕</button>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

export function TimezoneConverter() {
  const CITIES = [
    { label:"New York",       tz:"America/New_York",               region:"Americas" },
    { label:"Los Angeles",    tz:"America/Los_Angeles",            region:"Americas" },
    { label:"Chicago",        tz:"America/Chicago",                region:"Americas" },
    { label:"Toronto",        tz:"America/Toronto",                region:"Americas" },
    { label:"Vancouver",      tz:"America/Vancouver",              region:"Americas" },
    { label:"Mexico City",    tz:"America/Mexico_City",            region:"Americas" },
    { label:"São Paulo",      tz:"America/Sao_Paulo",              region:"Americas" },
    { label:"Buenos Aires",   tz:"America/Argentina/Buenos_Aires", region:"Americas" },
    { label:"Bogotá",         tz:"America/Bogota",                 region:"Americas" },
    { label:"Lima",           tz:"America/Lima",                   region:"Americas" },
    { label:"Santiago",       tz:"America/Santiago",               region:"Americas" },
    { label:"London",         tz:"Europe/London",                  region:"Europe" },
    { label:"Paris",          tz:"Europe/Paris",                   region:"Europe" },
    { label:"Berlin",         tz:"Europe/Berlin",                  region:"Europe" },
    { label:"Madrid",         tz:"Europe/Madrid",                  region:"Europe" },
    { label:"Rome",           tz:"Europe/Rome",                    region:"Europe" },
    { label:"Amsterdam",      tz:"Europe/Amsterdam",               region:"Europe" },
    { label:"Stockholm",      tz:"Europe/Stockholm",               region:"Europe" },
    { label:"Warsaw",         tz:"Europe/Warsaw",                  region:"Europe" },
    { label:"Athens",         tz:"Europe/Athens",                  region:"Europe" },
    { label:"Kyiv",           tz:"Europe/Kyiv",                    region:"Europe" },
    { label:"Moscow",         tz:"Europe/Moscow",                  region:"Europe" },
    { label:"Istanbul",       tz:"Europe/Istanbul",                region:"Europe" },
    { label:"Tel Aviv",       tz:"Asia/Jerusalem",                 region:"Middle East" },
    { label:"Beirut",         tz:"Asia/Beirut",                    region:"Middle East" },
    { label:"Dubai",          tz:"Asia/Dubai",                     region:"Middle East" },
    { label:"Riyadh",         tz:"Asia/Riyadh",                    region:"Middle East" },
    { label:"Cairo",          tz:"Africa/Cairo",                   region:"Africa" },
    { label:"Nairobi",        tz:"Africa/Nairobi",                 region:"Africa" },
    { label:"Lagos",          tz:"Africa/Lagos",                   region:"Africa" },
    { label:"Johannesburg",   tz:"Africa/Johannesburg",            region:"Africa" },
    { label:"Casablanca",     tz:"Africa/Casablanca",              region:"Africa" },
    { label:"Mumbai",         tz:"Asia/Kolkata",                   region:"Asia" },
    { label:"Delhi",          tz:"Asia/Kolkata",                   region:"Asia" },
    { label:"Karachi",        tz:"Asia/Karachi",                   region:"Asia" },
    { label:"Dhaka",          tz:"Asia/Dhaka",                     region:"Asia" },
    { label:"Bangkok",        tz:"Asia/Bangkok",                   region:"Asia" },
    { label:"Singapore",      tz:"Asia/Singapore",                 region:"Asia" },
    { label:"Kuala Lumpur",   tz:"Asia/Kuala_Lumpur",              region:"Asia" },
    { label:"Jakarta",        tz:"Asia/Jakarta",                   region:"Asia" },
    { label:"Manila",         tz:"Asia/Manila",                    region:"Asia" },
    { label:"Hong Kong",      tz:"Asia/Hong_Kong",                 region:"Asia" },
    { label:"Beijing",        tz:"Asia/Shanghai",                  region:"Asia" },
    { label:"Shanghai",       tz:"Asia/Shanghai",                  region:"Asia" },
    { label:"Tokyo",          tz:"Asia/Tokyo",                     region:"Asia" },
    { label:"Seoul",          tz:"Asia/Seoul",                     region:"Asia" },
    { label:"Sydney",         tz:"Australia/Sydney",               region:"Oceania" },
    { label:"Melbourne",      tz:"Australia/Melbourne",            region:"Oceania" },
    { label:"Brisbane",       tz:"Australia/Brisbane",             region:"Oceania" },
    { label:"Perth",          tz:"Australia/Perth",                region:"Oceania" },
    { label:"Auckland",       tz:"Pacific/Auckland",               region:"Oceania" },
    { label:"UTC",            tz:"UTC",                            region:"UTC" },
  ];

  const UTC_OFFSETS = [
    { offset:-12,   label:"UTC-12",    regions:"Baker Island, Howland Island" },
    { offset:-11,   label:"UTC-11",    regions:"American Samoa, Niue" },
    { offset:-10,   label:"UTC-10",    regions:"Hawaii, Cook Islands" },
    { offset:-9.5,  label:"UTC-9:30",  regions:"Marquesas Islands" },
    { offset:-9,    label:"UTC-9",     regions:"Alaska, Gambier Islands" },
    { offset:-8,    label:"UTC-8",     regions:"Los Angeles, Vancouver, Tijuana" },
    { offset:-7,    label:"UTC-7",     regions:"Denver, Phoenix, Calgary" },
    { offset:-6,    label:"UTC-6",     regions:"Chicago, Mexico City, Guatemala" },
    { offset:-5,    label:"UTC-5",     regions:"New York, Toronto, Lima, Bogota" },
    { offset:-4,    label:"UTC-4",     regions:"Santiago, Caracas, Halifax" },
    { offset:-3.5,  label:"UTC-3:30",  regions:"Newfoundland" },
    { offset:-3,    label:"UTC-3",     regions:"Sao Paulo, Buenos Aires, Montevideo" },
    { offset:-2,    label:"UTC-2",     regions:"South Georgia Island" },
    { offset:-1,    label:"UTC-1",     regions:"Azores, Cape Verde" },
    { offset:0,     label:"UTC+0",     regions:"London (winter), Dublin, Lisbon, Accra" },
    { offset:1,     label:"UTC+1",     regions:"Paris, Berlin, Rome, Lagos, Warsaw" },
    { offset:2,     label:"UTC+2",     regions:"Tel Aviv, Cairo, Athens, Johannesburg" },
    { offset:3,     label:"UTC+3",     regions:"Moscow, Nairobi, Riyadh, Kuwait" },
    { offset:3.5,   label:"UTC+3:30",  regions:"Tehran" },
    { offset:4,     label:"UTC+4",     regions:"Dubai, Baku, Tbilisi" },
    { offset:4.5,   label:"UTC+4:30",  regions:"Kabul" },
    { offset:5,     label:"UTC+5",     regions:"Karachi, Tashkent, Yekaterinburg" },
    { offset:5.5,   label:"UTC+5:30",  regions:"Mumbai, Delhi, Colombo" },
    { offset:5.75,  label:"UTC+5:45",  regions:"Kathmandu" },
    { offset:6,     label:"UTC+6",     regions:"Dhaka, Almaty, Omsk" },
    { offset:6.5,   label:"UTC+6:30",  regions:"Yangon (Rangoon)" },
    { offset:7,     label:"UTC+7",     regions:"Bangkok, Jakarta, Hanoi" },
    { offset:8,     label:"UTC+8",     regions:"Beijing, Singapore, Hong Kong, Perth" },
    { offset:9,     label:"UTC+9",     regions:"Tokyo, Seoul, Yakutsk" },
    { offset:9.5,   label:"UTC+9:30",  regions:"Adelaide, Darwin" },
    { offset:10,    label:"UTC+10",    regions:"Sydney, Melbourne, Vladivostok" },
    { offset:11,    label:"UTC+11",    regions:"Solomon Islands, Magadan" },
    { offset:12,    label:"UTC+12",    regions:"Auckland, Fiji, Kamchatka" },
    { offset:13,    label:"UTC+13",    regions:"Tonga, Samoa (DST)" },
    { offset:14,    label:"UTC+14",    regions:"Line Islands (Kiribati)" },
  ];

  const [tab, setTab]             = useState("city");
  const [fromLabel, setFromLabel] = useState("New York");
  const [inputTime, setInputTime] = useState(() => {
    const n = new Date();
    return String(n.getHours()).padStart(2,"0") + ":" + String(n.getMinutes()).padStart(2,"0");
  });
  const [myUtcOffset, setMyUtcOffset] = useState(0);
  const [filterRegion, setFilterRegion] = useState("All");

  // Meeting planner state
  const [meetCities, setMeetCities] = useState(["New York", "London", "Tokyo", "Dubai"]);
  const [meetAdd, setMeetAdd]       = useState("Tokyo");
  const [workStart, setWorkStart]   = useState(9);
  const [workEnd, setWorkEnd]       = useState(18);

  const regions = ["All", ...Array.from(new Set(CITIES.map(c => c.region)))];
  const fromCity = CITIES.find(c => c.label === fromLabel) || CITIES[0];

  const getHourInTz = (utcHour, tz) => {
    const d = new Date();
    d.setUTCHours(utcHour, 0, 0, 0);
    const h = parseInt(d.toLocaleString("en-US", { timeZone: tz, hour:"numeric", hour12:false }), 10);
    return isNaN(h) ? 0 : h % 24;
  };

  const convert = (toTz) => {
    const parts = inputTime.split(":");
    const h = parseInt(parts[0], 10);
    const m = parseInt(parts[1], 10);
    if (isNaN(h) || isNaN(m)) return { time:"--:--", period:"", offset:"" };
    const now = new Date();
    now.setHours(h, m, 0, 0);
    const fromStr = now.toLocaleString("en-US", { timeZone: fromCity.tz });
    const toStr   = now.toLocaleString("en-US", { timeZone: toTz });
    const fromDate = new Date(fromStr);
    const toDate2  = new Date(toStr);
    const diffMs   = toDate2 - fromDate;
    const result   = new Date(now.getTime() + diffMs);
    const rh = result.getHours();
    const rm = result.getMinutes();
    const timeStr  = String(rh).padStart(2,"0") + ":" + String(rm).padStart(2,"0");
    const period   = rh < 6 ? "Night" : rh < 12 ? "Morning" : rh < 17 ? "Afternoon" : rh < 21 ? "Evening" : "Night";
    const periodEmoji = rh < 6 ? "🌙" : rh < 12 ? "🌅" : rh < 17 ? "☀️" : rh < 21 ? "🌆" : "🌙";
    const offH     = Math.floor(Math.abs(diffMs) / 36e5);
    const offSign  = diffMs >= 0 ? "+" : "-";
    const offsetStr = diffMs === 0 ? "same time" : offSign + offH + "h";
    return { time: timeStr, period: periodEmoji + " " + period, offset: offsetStr };
  };

  const diffColor = (diff) => {
    if (diff === 0) return T.green;
    if (Math.abs(diff) <= 3) return T.blue;
    if (Math.abs(diff) <= 6) return T.gold;
    return T.accent;
  };

  const filteredCities = filterRegion === "All" ? CITIES : CITIES.filter(c => c.region === filterRegion);

  // Meeting planner: find UTC hours where all cities are within workStart–workEnd
  const meetingSlots = Array.from({ length: 24 }, (_, utcH) => {
    const cityHours = meetCities.map(label => {
      const city = CITIES.find(c => c.label === label);
      if (!city) return null;
      return { label, hour: getHourInTz(utcH, city.tz) };
    }).filter(Boolean);
    const allInRange = cityHours.every(c => c.hour >= workStart && c.hour < workEnd);
    return { utcHour: utcH, cityHours, allInRange };
  }).filter(s => s.allInRange);

  const tabBtn = (id, label) => (
    <button key={id} onClick={() => setTab(id)}
      style={{ flex:1, padding:"8px 0", borderRadius:9, border:"1.5px solid " + (tab===id ? T.teal : T.border), background:tab===id ? T.tealDim : T.card, color:tab===id ? T.teal : T.muted, fontSize:11, fontFamily:"Syne, sans-serif", fontWeight:700, cursor:"pointer" }}>
      {label}
    </button>
  );

  return (
    <div>
      {/* Tab bar */}
      <div style={{ display:"flex", gap:6, marginBottom:16 }}>
        {tabBtn("city",    "🌆 City")}
        {tabBtn("utc",     "🕐 UTC Offset")}
        {tabBtn("meeting", "📅 Meeting Planner")}
      </div>

      {/* ── City Converter ── */}
      {tab === "city" && (
        <div>
          <Row label="Convert from">
            <select value={fromLabel} onChange={e => setFromLabel(e.target.value)} style={inputStyle}>
              {CITIES.map(c => <option key={c.label} value={c.label}>{c.label}</option>)}
            </select>
          </Row>
          <Row label="Time">
            <input type="time" value={inputTime} onChange={e => setInputTime(e.target.value)} style={inputStyle} />
          </Row>
          <div style={{ display:"flex", gap:6, marginBottom:12, flexWrap:"wrap" }}>
            {regions.map(r => (
              <button key={r} onClick={() => setFilterRegion(r)}
                style={{ padding:"5px 10px", borderRadius:99, border:"1px solid " + (filterRegion===r ? T.teal : T.border), background:filterRegion===r ? T.tealDim : T.card, color:filterRegion===r ? T.teal : T.muted, fontSize:11, fontFamily:"DM Sans, sans-serif", cursor:"pointer" }}>
                {r}
              </button>
            ))}
          </div>
          <div style={{ display:"flex", flexDirection:"column", gap:6 }}>
            {filteredCities.filter(z => z.label !== fromLabel).map(z => {
              const r = convert(z.tz);
              return (
                <div key={z.label} style={{ display:"flex", alignItems:"center", justifyContent:"space-between", padding:"10px 13px", borderRadius:9, background:T.card, border:"1px solid " + T.border }}>
                  <div>
                    <div style={{ fontFamily:"Syne, sans-serif", fontWeight:700, fontSize:12, color:T.ink }}>{z.label}</div>
                    <div style={{ fontSize:10, color:T.muted, fontFamily:"DM Sans, sans-serif" }}>{z.region} · {r.period}</div>
                  </div>
                  <div style={{ textAlign:"right" }}>
                    <div style={{ fontFamily:"Syne, sans-serif", fontWeight:800, fontSize:18, color:T.teal }}>{r.time}</div>
                    <div style={{ fontSize:10, color:T.muted, fontFamily:"DM Sans, sans-serif" }}>{r.offset}</div>
                  </div>
                </div>
              );
            })}
          </div>
          <div style={{ marginTop:10 }}>
            <CopyButton text={CITIES.filter(z => z.label !== fromLabel).map(z => { const r = convert(z.tz); return z.label + ": " + r.time; }).join("\n")} />
          </div>
        </div>
      )}

      {/* ── UTC Offset Tool ── */}
      {tab === "utc" && (
        <div>
          <Row label="Your UTC offset">
            <select value={myUtcOffset} onChange={e => setMyUtcOffset(Number(e.target.value))} style={inputStyle}>
              {UTC_OFFSETS.map(u => (
                <option key={u.offset} value={u.offset}>{u.label} — {u.regions}</option>
              ))}
            </select>
          </Row>
          <div style={{ fontSize:11, color:T.muted, marginBottom:12, fontFamily:"DM Sans, sans-serif" }}>
            Hour difference between you ({UTC_OFFSETS.find(u => u.offset === myUtcOffset)?.label}) and every other timezone:
          </div>
          <div style={{ display:"flex", flexDirection:"column", gap:5 }}>
            {UTC_OFFSETS.filter(u => u.offset !== myUtcOffset).map(u => {
              const diff = u.offset - myUtcOffset;
              const sign = diff > 0 ? "+" : "";
              const hrs  = Math.floor(Math.abs(diff));
              const mins = Math.round((Math.abs(diff) - hrs) * 60);
              const diffStr = mins ? sign + (diff < 0 ? "-" : "") + hrs + "h " + mins + "m" : sign + diff + "h";
              return (
                <div key={u.offset} style={{ display:"flex", alignItems:"flex-start", justifyContent:"space-between", padding:"10px 13px", borderRadius:9, background:T.card, border:"1px solid " + T.border }}>
                  <div>
                    <div style={{ fontFamily:"Syne, sans-serif", fontWeight:700, fontSize:12, color:T.ink, marginBottom:2 }}>{u.label}</div>
                    <div style={{ fontFamily:"DM Sans, sans-serif", fontSize:11, color:T.muted }}>{u.regions}</div>
                  </div>
                  <div style={{ fontFamily:"Syne, sans-serif", fontWeight:800, fontSize:14, color:diffColor(diff), minWidth:52, textAlign:"right", paddingTop:2 }}>
                    {diffStr}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* ── Meeting Planner ── */}
      {tab === "meeting" && (
        <div>
          <div style={{ fontSize:12, color:T.muted, marginBottom:12, fontFamily:"DM Sans, sans-serif", lineHeight:1.6 }}>
            Find the best time to meet across multiple cities. Highlights hours when everyone is within working hours.
          </div>

          {/* Work hours range */}
          <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:10, marginBottom:12 }}>
            <div>
              <div style={{ fontSize:10, color:T.muted, fontFamily:"Syne, sans-serif", fontWeight:700, marginBottom:4 }}>WORK DAY STARTS</div>
              <select value={workStart} onChange={e => setWorkStart(Number(e.target.value))} style={inputStyle}>
                {Array.from({length:24}, (_,i) => <option key={i} value={i}>{String(i).padStart(2,"0")}:00</option>)}
              </select>
            </div>
            <div>
              <div style={{ fontSize:10, color:T.muted, fontFamily:"Syne, sans-serif", fontWeight:700, marginBottom:4 }}>WORK DAY ENDS</div>
              <select value={workEnd} onChange={e => setWorkEnd(Number(e.target.value))} style={inputStyle}>
                {Array.from({length:24}, (_,i) => <option key={i} value={i}>{String(i).padStart(2,"0")}:00</option>)}
              </select>
            </div>
          </div>

          {/* City chips */}
          <div style={{ fontSize:10, color:T.muted, fontFamily:"Syne, sans-serif", fontWeight:700, marginBottom:6 }}>CITIES</div>
          <div style={{ display:"flex", flexWrap:"wrap", gap:6, marginBottom:10 }}>
            {meetCities.map(city => (
              <div key={city} style={{ display:"flex", alignItems:"center", gap:5, padding:"5px 10px", borderRadius:99, background:T.tealDim, border:"1px solid " + T.teal }}>
                <span style={{ fontSize:11, color:T.teal, fontFamily:"Syne, sans-serif", fontWeight:700 }}>{city}</span>
                <span onClick={() => setMeetCities(cs => cs.filter(c => c !== city))}
                  style={{ fontSize:11, color:T.teal, cursor:"pointer", lineHeight:1, opacity:0.7 }}>✕</span>
              </div>
            ))}
          </div>
          <div style={{ display:"flex", gap:8, marginBottom:16 }}>
            <select value={meetAdd} onChange={e => setMeetAdd(e.target.value)} style={{ ...inputStyle, flex:1 }}>
              {CITIES.filter(c => !meetCities.includes(c.label)).map(c => (
                <option key={c.label} value={c.label}>{c.label}</option>
              ))}
            </select>
            <button onClick={() => { if (meetAdd && !meetCities.includes(meetAdd)) setMeetCities(cs => [...cs, meetAdd]); }}
              style={{ padding:"9px 14px", borderRadius:9, border:"none", background:T.teal, color:"white", fontFamily:"Syne, sans-serif", fontWeight:700, fontSize:12, cursor:"pointer", flexShrink:0 }}>
              + Add
            </button>
          </div>

          {/* Results */}
          {meetCities.length < 2 ? (
            <div style={{ padding:"16px", textAlign:"center", color:T.muted, fontSize:12, fontFamily:"DM Sans, sans-serif", background:T.card, borderRadius:10, border:"1px solid " + T.border }}>
              Add at least 2 cities to find overlap windows
            </div>
          ) : meetingSlots.length === 0 ? (
            <div style={{ padding:"16px", textAlign:"center", borderRadius:10, background:"#fef2f2", border:"1px solid #fecaca" }}>
              <div style={{ fontSize:20, marginBottom:6 }}>😬</div>
              <div style={{ fontFamily:"Syne, sans-serif", fontWeight:700, fontSize:13, color:"#dc2626", marginBottom:4 }}>No overlap found</div>
              <div style={{ fontSize:11, color:"#dc2626", opacity:0.8, fontFamily:"DM Sans, sans-serif" }}>
                Try widening work hours or removing a city from a very different timezone
              </div>
            </div>
          ) : (
            <div>
              <div style={{ fontSize:10, color:T.teal, fontFamily:"Syne, sans-serif", fontWeight:700, marginBottom:8 }}>
                {meetingSlots.length} WINDOW{meetingSlots.length !== 1 ? "S" : ""} WORK FOR EVERYONE
              </div>
              <div style={{ display:"flex", flexDirection:"column", gap:6 }}>
                {meetingSlots.map(slot => (
                  <div key={slot.utcHour} style={{ padding:"12px 14px", borderRadius:10, background:T.card, border:"1px solid " + T.teal + "44" }}>
                    <div style={{ fontSize:10, color:T.muted, fontFamily:"Syne, sans-serif", fontWeight:700, marginBottom:6 }}>
                      {"UTC " + String(slot.utcHour).padStart(2,"0") + ":00"}
                    </div>
                    <div style={{ display:"flex", flexWrap:"wrap", gap:8 }}>
                      {slot.cityHours.map(ch => {
                        const h = ch.hour;
                        const timeStr = String(h).padStart(2,"0") + ":00";
                        const emoji = h < 6 ? "🌙" : h < 12 ? "🌅" : h < 17 ? "☀️" : h < 21 ? "🌆" : "🌙";
                        return (
                          <div key={ch.label} style={{ display:"flex", alignItems:"center", gap:5, padding:"4px 10px", borderRadius:8, background:T.tealDim }}>
                            <span style={{ fontSize:12 }}>{emoji}</span>
                            <div>
                              <div style={{ fontSize:10, color:T.muted, fontFamily:"DM Sans, sans-serif" }}>{ch.label}</div>
                              <div style={{ fontFamily:"Syne, sans-serif", fontWeight:700, fontSize:13, color:T.teal }}>{timeStr}</div>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                ))}
              </div>
              <div style={{ marginTop:10 }}>
                <CopyButton text={meetingSlots.map(slot => "UTC " + String(slot.utcHour).padStart(2,"0") + ":00 — " + slot.cityHours.map(ch => ch.label + " " + String(ch.hour).padStart(2,"0") + ":00").join(", ")).join("\n")} />
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export function UnitConverter() {
  const CATS = {
    "📏 Length":      { icon:"📏", units:["mm","cm","m","km","in","ft","yd","mi","nmi"], toBase:{ mm:.001,cm:.01,m:1,km:1000,in:.0254,ft:.3048,yd:.9144,mi:1609.344,nmi:1852 } },
    "⚖️ Weight":      { icon:"⚖️", units:["mg","g","kg","t","oz","lb","st"], toBase:{ mg:1e-6,g:.001,kg:1,t:1000,oz:.0283495,lb:.453592,st:6.35029 } },
    "🌡️ Temperature": { icon:"🌡️", units:["°C","°F","K"], toBase:null },
    "💧 Volume":      { icon:"💧", units:["ml","cl","dl","L","fl oz","cup","pt","qt","gal","tbsp","tsp"], toBase:{ ml:.001,cl:.01,dl:.1,L:1,"fl oz":.0295735,cup:.236588,pt:.473176,qt:.946353,gal:3.78541,tbsp:.0147868,tsp:.00492892 } },
    "📐 Area":        { icon:"📐", units:["mm²","cm²","m²","km²","in²","ft²","yd²","acre","ha"], toBase:{ "mm²":1e-6,"cm²":.0001,"m²":1,"km²":1e6,"in²":.00064516,"ft²":.092903,"yd²":.836127,acre:4046.86,ha:10000 } },
    "💨 Speed":       { icon:"💨", units:["m/s","km/h","mph","knots","ft/s"], toBase:{ "m/s":1,"km/h":1/3.6,mph:0.44704,knots:0.514444,"ft/s":0.3048 } },
    "💾 Data":        { icon:"💾", units:["bit","B","KB","MB","GB","TB","PB"], toBase:{ bit:1,B:8,KB:8192,MB:8388608,GB:8589934592,TB:8796093022208,PB:9007199254740992 } },
    "🍳 Cooking":     { icon:"🍳", units:["tsp","tbsp","fl oz","cup","pt","qt","gal","ml","L"], toBase:{ tsp:.00492892,tbsp:.0147868,"fl oz":.0295735,cup:.236588,pt:.473176,qt:.946353,gal:3.78541,ml:.001,L:1 } },
  };

  const [catKey, setCatKey] = useState("📏 Length");
  const [fromUnit, setFromUnit] = useState("m");
  const [toUnit, setToUnit] = useState("ft");
  const [value, setValue] = useState("1");

  const cat = CATS[catKey];

  const switchCat = (k) => {
    setCatKey(k);
    setFromUnit(CATS[k].units[0]);
    setToUnit(CATS[k].units[1]);
    setValue("1");
  };

  const swapUnits = () => { setFromUnit(toUnit); setToUnit(fromUnit); };

  const convert = () => {
    const v = Number(value);
    if (isNaN(v) || value === "") return "—";
    if (catKey === "🌡️ Temperature") {
      if (fromUnit === toUnit) return String(v);
      if (fromUnit === "°C" && toUnit === "°F") return (v * 9/5 + 32).toFixed(4).replace(/\.?0+$/, "");
      if (fromUnit === "°C" && toUnit === "K")  return (v + 273.15).toFixed(4).replace(/\.?0+$/, "");
      if (fromUnit === "°F" && toUnit === "°C") return ((v - 32) * 5/9).toFixed(4).replace(/\.?0+$/, "");
      if (fromUnit === "°F" && toUnit === "K")  return ((v - 32) * 5/9 + 273.15).toFixed(4).replace(/\.?0+$/, "");
      if (fromUnit === "K"  && toUnit === "°C") return (v - 273.15).toFixed(4).replace(/\.?0+$/, "");
      if (fromUnit === "K"  && toUnit === "°F") return ((v - 273.15) * 9/5 + 32).toFixed(4).replace(/\.?0+$/, "");
    }
    if (catKey === "💾 Data") {
      const inBits = v * cat.toBase[fromUnit];
      const result = inBits / cat.toBase[toUnit];
      return result >= 1000 ? result.toFixed(4).replace(/\.?0+$/, "") : result.toPrecision(6).replace(/\.?0+$/, "");
    }
    const result = v * cat.toBase[fromUnit] / cat.toBase[toUnit];
    if (Math.abs(result) < 0.000001 && result !== 0) return result.toExponential(4);
    return result.toFixed(6).replace(/\.?0+$/, "");
  };

  const result = convert();

  return (
    <div>
      {/* Category tabs */}
      <div style={{ marginBottom: 16 }}>
        <div style={{ fontSize: 11, color: T.muted, marginBottom: 8, fontFamily: "DM Sans, sans-serif", letterSpacing: 0.3 }}>Category</div>
        <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
          {Object.keys(CATS).map(k => (
            <button key={k} onClick={() => switchCat(k)} style={{ padding: "6px 11px", borderRadius: 9, border: `1.5px solid ${catKey === k ? T.accent : T.border}`, background: catKey === k ? T.accentDim : "white", color: catKey === k ? T.accent : T.muted, fontSize: 11, fontFamily: "Syne, sans-serif", fontWeight: 700, cursor: "pointer", whiteSpace: "nowrap" }}>
              {k}
            </button>
          ))}
        </div>
      </div>

      {/* Value input */}
      <Row label="Value">
        <input type="number" value={value} onChange={e => setValue(e.target.value)} style={inputStyle} />
      </Row>

      {/* From / Swap / To */}
      <div style={{ display: "grid", gridTemplateColumns: "1fr 36px 1fr", gap: 8, alignItems: "end", marginBottom: 14 }}>
        <Row label="From">
          <select value={fromUnit} onChange={e => setFromUnit(e.target.value)} style={inputStyle}>
            {cat.units.map(u => <option key={u}>{u}</option>)}
          </select>
        </Row>
        <button onClick={swapUnits} style={{ height: 38, marginBottom: 0, borderRadius: 9, border: `1.5px solid ${T.border}`, background: "white", color: T.muted, fontSize: 16, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center" }}>⇄</button>
        <Row label="To">
          <select value={toUnit} onChange={e => setToUnit(e.target.value)} style={inputStyle}>
            {cat.units.map(u => <option key={u}>{u}</option>)}
          </select>
        </Row>
      </div>

      <Result label={`${value || 0} ${fromUnit} =`} value={`${result} ${toUnit}`} />
      <CopyButton text={`${value} ${fromUnit} = ${result} ${toUnit} — ToolForge`} />
    </div>
  );
}

export function StudyPlanner() {
  const TECHNIQUES = [
    { id:"pomodoro", label:"🍅 Pomodoro",       desc:"25 min focus, 5 min break", mins:30,  longMins:25 },
    { id:"deep",     label:"🧠 Deep Work",       desc:"90 min uninterrupted blocks", mins:90, longMins:90 },
    { id:"spaced",   label:"🔁 Spaced Repetition", desc:"Short daily reviews, spaced out", mins:30, longMins:30 },
    { id:"custom",   label:"⚙️ Custom",           desc:"Set your own session length", mins:45, longMins:45 },
  ];

  const [subject, setSubject]     = useState("");
  const [hours, setHours]         = useState("");
  const [days, setDays]           = useState("");
  const [technique, setTech]      = useState("pomodoro");
  const [customMins, setCustomMins] = useState(45);

  const tech      = TECHNIQUES.find(t => t.id === technique);
  const sessMins  = technique === "custom" ? Number(customMins) : tech.longMins;
  const hoursNum  = parseFloat(hours) || 0;
  const daysNum   = parseInt(days) || 0;
  const hasResult = hoursNum > 0 && daysNum > 0 && sessMins > 0;

  const totalMins   = hoursNum * 60;
  const sessions    = hasResult ? Math.ceil(totalMins / sessMins) : 0;
  const perDay      = hasResult ? Math.ceil(sessions / daysNum) : 0;
  const minsPerDay  = perDay * sessMins;
  const hrsPerDay   = (minsPerDay / 60).toFixed(1);

  const schedule = hasResult ? Array.from({ length: Math.min(daysNum, 7) }, (_, i) => ({
    day: "Day " + (i + 1),
    sessions: i < daysNum ? perDay : 0,
  })) : [];

  return (
    <div>
      <Row label="Subject / Topic">
        <input value={subject} onChange={e => setSubject(e.target.value)}
          style={inputStyle} placeholder="e.g. Calculus, Spanish, History" />
      </Row>

      <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:10 }}>
        <Row label="Total Hours Needed"><NumInput val={hours} set={setHours} /></Row>
        <Row label="Days Available"><NumInput val={days} set={setDays} /></Row>
      </div>

      {/* Technique picker */}
      <div style={{ marginBottom:14 }}>
        <div style={{ fontSize:10, color:T.muted, fontFamily:"Syne, sans-serif", fontWeight:700, marginBottom:6 }}>STUDY TECHNIQUE</div>
        <div style={{ display:"flex", flexDirection:"column", gap:6 }}>
          {TECHNIQUES.map(t => (
            <div key={t.id} onClick={() => setTech(t.id)}
              style={{ padding:"10px 13px", borderRadius:10, border:`1px solid ${technique===t.id?T.purple:T.border}`, background:technique===t.id?T.purpleDim:T.card, cursor:"pointer", transition:"all 0.15s", display:"flex", alignItems:"center", justifyContent:"space-between" }}>
              <div>
                <div style={{ fontFamily:"Syne, sans-serif", fontWeight:700, fontSize:12, color:technique===t.id?T.purple:T.ink }}>{t.label}</div>
                <div style={{ fontSize:11, color:T.muted, fontFamily:"DM Sans, sans-serif", marginTop:1 }}>{t.desc}</div>
              </div>
              {technique===t.id && <div style={{ width:8, height:8, borderRadius:"50%", background:T.purple, flexShrink:0 }} />}
            </div>
          ))}
        </div>
        {technique === "custom" && (
          <div style={{ marginTop:8 }}>
            <Row label="Session Length (minutes)"><NumInput val={customMins} set={setCustomMins} /></Row>
          </div>
        )}
      </div>

      {/* Results */}
      {hasResult && (
        <>
          <div style={{ marginTop:4, padding:"16px 18px", borderRadius:14, background:T.card, border:`2px solid ${T.purple}22` }}>
            <div style={{ fontFamily:"Syne, sans-serif", fontWeight:700, fontSize:11, color:T.muted, marginBottom:10, letterSpacing:0.5 }}>YOUR STUDY PLAN{subject ? " FOR " + subject.toUpperCase() : ""}</div>
            <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr 1fr", gap:8, marginBottom:12 }}>
              <div style={{ textAlign:"center", padding:"10px 6px", borderRadius:10, background:T.purpleDim }}>
                <div style={{ fontFamily:"Syne, sans-serif", fontWeight:800, fontSize:22, color:T.purple }}>{sessions}</div>
                <div style={{ fontSize:10, color:T.muted, fontFamily:"DM Sans, sans-serif", marginTop:2 }}>total sessions</div>
              </div>
              <div style={{ textAlign:"center", padding:"10px 6px", borderRadius:10, background:T.purpleDim }}>
                <div style={{ fontFamily:"Syne, sans-serif", fontWeight:800, fontSize:22, color:T.purple }}>{perDay}</div>
                <div style={{ fontSize:10, color:T.muted, fontFamily:"DM Sans, sans-serif", marginTop:2 }}>sessions/day</div>
              </div>
              <div style={{ textAlign:"center", padding:"10px 6px", borderRadius:10, background:T.purpleDim }}>
                <div style={{ fontFamily:"Syne, sans-serif", fontWeight:800, fontSize:22, color:T.purple }}>{hrsPerDay}h</div>
                <div style={{ fontSize:10, color:T.muted, fontFamily:"DM Sans, sans-serif", marginTop:2 }}>per day</div>
              </div>
            </div>
            <div style={{ fontSize:12, color:T.purple, fontFamily:"DM Sans, sans-serif", textAlign:"center", padding:"8px", borderRadius:8, background:T.purpleDim }}>
              {sessMins} min sessions · {daysNum} days · {hoursNum}h total
            </div>
          </div>

          {/* Mini weekly schedule */}
          {daysNum <= 14 && (
            <div style={{ marginTop:10 }}>
              <div style={{ fontSize:10, color:T.muted, fontFamily:"Syne, sans-serif", fontWeight:700, marginBottom:6 }}>WEEK PREVIEW</div>
              <div style={{ display:"flex", gap:5, flexWrap:"wrap" }}>
                {schedule.map((d, i) => (
                  <div key={i} style={{ flex:"0 0 auto", minWidth:48, padding:"8px 6px", borderRadius:8, background:T.purpleDim, border:`1px solid ${T.purple}33`, textAlign:"center" }}>
                    <div style={{ fontSize:9, color:T.muted, fontFamily:"DM Sans, sans-serif" }}>{d.day}</div>
                    <div style={{ fontFamily:"Syne, sans-serif", fontWeight:700, fontSize:13, color:T.purple, marginTop:2 }}>{d.sessions}×</div>
                  </div>
                ))}
                {daysNum > 7 && <div style={{ flex:"0 0 auto", padding:"8px 6px", borderRadius:8, background:T.card, border:`1px solid ${T.border}`, fontSize:10, color:T.muted, fontFamily:"DM Sans, sans-serif", display:"flex", alignItems:"center" }}>+{daysNum-7} more</div>}
              </div>
            </div>
          )}

          <div style={{ marginTop:10 }}>
            <CopyButton text={"Study plan" + (subject ? " for " + subject : "") + ": " + perDay + " sessions/day (" + sessMins + "min each) for " + daysNum + " days — ToolForge"} />
          </div>
          <Tip>Consistency beats cramming. Even one session a day compounds fast.</Tip>
        </>
      )}
    </div>
  );
}

export function CitationFormatter({ proToken, onNeedUpgrade, onTokenUpdate }) {
  const [style, setStyle]       = useState("APA");
  const [type, setType]         = useState("website");
  const [author, setAuthor]     = useState("");
  const [title, setTitle]       = useState("");
  const [year, setYear]         = useState("");
  const [publisher, setPub]     = useState("");
  const [journal, setJournal]   = useState("");
  const [volume, setVolume]     = useState("");
  const [pages, setPages]       = useState("");
  const [url, setUrl]           = useState("");
  const [autoUrl, setAutoUrl]   = useState("");
  const [loadingAuto, setLoadingAuto] = useState(false);
  const [autoError, setAutoError]     = useState("");

  const hasClaude = proToken && proToken.generations_left >= 1;

  const SOURCE_TYPES = [
    { id:"website",  label:"🌐 Website"  },
    { id:"book",     label:"📖 Book"     },
    { id:"journal",  label:"📄 Journal"  },
    { id:"youtube",  label:"▶️ YouTube"  },
  ];

  const cite = () => {
    const a  = author    || "Author, A.";
    const t  = title     || "Title";
    const y  = year      || "n.d.";
    const p  = publisher || "Publisher";
    const j  = journal   || "Journal Name";
    const v  = volume    || "1";
    const pg = pages     || "1–10";
    const u  = url;

    if (style === "APA") {
      if (type === "website") return `${a} (${y}). ${t}. ${u ? u : ""}`.trim();
      if (type === "book")    return `${a} (${y}). *${t}*. ${p}.`;
      if (type === "journal") return `${a} (${y}). ${t}. *${j}*, *${v}*, ${pg}.`;
      if (type === "youtube") return `${a} [${a}]. (${y}). *${t}* [Video]. YouTube. ${u}`;
    }
    if (style === "MLA") {
      if (type === "website") return `${a} "${t}." ${y}${u ? ", " + u : ""}.`;
      if (type === "book")    return `${a} *${t}*. ${p}, ${y}.`;
      if (type === "journal") return `${a} "${t}." *${j}*, vol. ${v}, ${y}, pp. ${pg}.`;
      if (type === "youtube") return `${a} "${t}." *YouTube*, ${y}, ${u}.`;
    }
    if (style === "Chicago") {
      if (type === "website") return `${a} "${t}." Accessed ${y}. ${u}`;
      if (type === "book")    return `${a} *${t}*. ${p}, ${y}.`;
      if (type === "journal") return `${a} "${t}." *${j}* ${v} (${y}): ${pg}.`;
      if (type === "youtube") return `${a} "${t}." YouTube video. ${y}. ${u}`;
    }
    return "";
  };

  const autoFill = async () => {
    if (!autoUrl.trim()) return;
    if (!hasClaude) { onNeedUpgrade(); return; }
    setLoadingAuto(true); setAutoError("");
    const prompt = `Extract citation metadata from this URL: ${autoUrl}

If you can infer the page content from the URL itself (e.g. a Wikipedia article, news site, YouTube video), do so. Otherwise use what you know.

Return ONLY a JSON object with these fields (use empty string "" if unknown):
{
  "author": "Last, F. format if possible",
  "title": "page or article title",
  "year": "publication year as 4-digit string",
  "publisher": "website name or publisher",
  "type": "website | book | journal | youtube"
}

No explanation, no markdown, just the raw JSON object.`;
    try {
      const res  = await fetch("/api/generate-claude", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ token:proToken.token, toolName:"Citation Formatter", userInput:prompt, tokensToDeduct:1 }) });
      const data = await res.json();
      if (!res.ok) { setAutoError(data.error || "Auto-fill failed."); setLoadingAuto(false); return; }
      const raw  = data.result.replace(/```json|```/g,"").trim();
      const obj  = JSON.parse(raw);
      if (obj.author)    setAuthor(obj.author);
      if (obj.title)     setTitle(obj.title);
      if (obj.year)      setYear(obj.year);
      if (obj.publisher) setPub(obj.publisher);
      if (obj.type && SOURCE_TYPES.find(s => s.id === obj.type)) setType(obj.type);
      setUrl(autoUrl);
      onTokenUpdate({ ...proToken, generations_left: data.generations_left });
    } catch { setAutoError("Couldn't parse response. Fill in fields manually."); }
    setLoadingAuto(false);
  };

  const citation = cite();

  return (
    <div>
      {/* Auto-fill from URL */}
      <div style={{ marginBottom:16, padding:14, borderRadius:12, border:`2px solid ${T.purple}44`, background:T.purpleDim }}>
        <div style={{ fontFamily:"Syne, sans-serif", fontWeight:800, fontSize:13, color:T.purple, marginBottom:4 }}>✦ Auto-fill from URL</div>
        <div style={{ fontSize:12, color:T.purple, fontFamily:"DM Sans, sans-serif", marginBottom:10, opacity:0.8 }}>Paste any URL and Claude will extract the citation fields for you.</div>
        <div style={{ display:"flex", gap:8 }}>
          <input value={autoUrl} onChange={e=>setAutoUrl(e.target.value)} placeholder="https://..." style={{ ...inputStyle, flex:1, margin:0 }} onKeyDown={e=>e.key==="Enter"&&autoFill()} />
          <button onClick={autoFill} disabled={loadingAuto || !autoUrl.trim()} style={{ padding:"0 14px", borderRadius:9, border:"none", background:(!autoUrl.trim()||loadingAuto)?T.border:T.purple, color:(!autoUrl.trim()||loadingAuto)?T.muted:"white", fontFamily:"Syne, sans-serif", fontWeight:700, fontSize:12, cursor:autoUrl.trim()&&!loadingAuto?"pointer":"default", whiteSpace:"nowrap" }}>
            {loadingAuto ? "Filling…" : hasClaude ? "Auto-fill · 1 token" : "Unlock"}
          </button>
        </div>
        {autoError && <div style={{ marginTop:8, fontSize:11, color:"#dc2626", fontFamily:"DM Sans, sans-serif" }}>{autoError}</div>}
      </div>

      {/* Style */}
      <div style={{ marginBottom:14 }}>
        <div style={{ fontSize:11, color:T.muted, marginBottom:6, fontFamily:"DM Sans, sans-serif", letterSpacing:0.3 }}>Citation Style</div>
        <div style={{ display:"flex", gap:6 }}>
          {["APA","MLA","Chicago"].map(s => (
            <button key={s} onClick={()=>setStyle(s)} style={{ flex:1, padding:"8px 0", borderRadius:9, border:`1.5px solid ${style===s?T.purple:T.border}`, background:style===s?T.purpleDim:"white", color:style===s?T.purple:T.muted, fontSize:12, fontFamily:"Syne, sans-serif", fontWeight:700, cursor:"pointer" }}>{s}</button>
          ))}
        </div>
      </div>

      {/* Source Type */}
      <div style={{ marginBottom:14 }}>
        <div style={{ fontSize:11, color:T.muted, marginBottom:6, fontFamily:"DM Sans, sans-serif", letterSpacing:0.3 }}>Source Type</div>
        <div style={{ display:"flex", gap:6, flexWrap:"wrap" }}>
          {SOURCE_TYPES.map(tp => (
            <button key={tp.id} onClick={()=>setType(tp.id)} style={{ padding:"7px 12px", borderRadius:9, border:`1.5px solid ${type===tp.id?T.purple:T.border}`, background:type===tp.id?T.purpleDim:"white", color:type===tp.id?T.purple:T.muted, fontSize:11, fontFamily:"Syne, sans-serif", fontWeight:700, cursor:"pointer" }}>{tp.label}</button>
          ))}
        </div>
      </div>

      <Row label="Author (Last, F.)"><input value={author} onChange={e=>setAuthor(e.target.value)} placeholder="e.g. Smith, J." style={inputStyle} /></Row>
      <Row label="Title"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. The Art of Learning" style={inputStyle} /></Row>
      <Row label="Year"><input value={year} onChange={e=>setYear(e.target.value)} placeholder="e.g. 2023" style={inputStyle} /></Row>

      {type === "book"    && <Row label="Publisher"><input value={publisher} onChange={e=>setPub(e.target.value)} placeholder="e.g. Penguin Press" style={inputStyle} /></Row>}
      {type === "journal" && <>
        <Row label="Journal Name"><input value={journal} onChange={e=>setJournal(e.target.value)} placeholder="e.g. Nature" style={inputStyle} /></Row>
        <Row label="Volume"><input value={volume} onChange={e=>setVolume(e.target.value)} placeholder="e.g. 12" style={inputStyle} /></Row>
        <Row label="Pages"><input value={pages} onChange={e=>setPages(e.target.value)} placeholder="e.g. 45–67" style={inputStyle} /></Row>
      </>}
      {(type === "website" || type === "youtube") && <Row label="URL"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..." style={inputStyle} /></Row>}

      <div className="tf-citation-result" style={{ marginTop:14, padding:14, borderRadius:10, background:T.purpleDim, border:`1px solid ${T.purple}33`, fontSize:13, color:T.ink, fontFamily:"DM Sans, sans-serif", lineHeight:1.8, userSelect:"all" }}>
        {citation}
      </div>
      <CopyButton text={citation} />
    </div>
  );
}

export function WordCounter() {
  const [text, setText] = useState("");
  const words = text.trim() === "" ? 0 : text.trim().split(/\s+/).length;
  const chars = text.length;
  const charsNoSpaces = text.replace(/\s/g, "").length;
  const sentences = text.trim() === "" ? 0 : (text.match(/[.!?]+/g) || []).length;
  const paragraphs = text.trim() === "" ? 0 : text.split(/\n\s*\n/).filter(p => p.trim()).length;
  const readingTime = Math.max(1, Math.ceil(words / 200));
  const stats = [
    { label: "Words", value: words.toLocaleString(), color: T.accent },
    { label: "Characters", value: chars.toLocaleString(), color: T.blue },
    { label: "No Spaces", value: charsNoSpaces.toLocaleString(), color: T.purple },
    { label: "Sentences", value: sentences.toLocaleString(), color: T.teal },
    { label: "Paragraphs", value: paragraphs.toLocaleString(), color: T.gold },
    { label: "Reading Time", value: `~${readingTime}min`, color: "#dc2626" },
  ];
  return (
    <div>
      <textarea value={text} onChange={e => setText(e.target.value)} placeholder="Paste or type your text here…" style={{ width: "100%", minHeight: 200, padding: "13px 14px", border: `1.5px solid ${T.border}`, borderRadius: 10, fontSize: 14, fontFamily: "DM Sans, sans-serif", color: T.ink, background: "#fdfcfb", resize: "vertical", outline: "none", boxSizing: "border-box", lineHeight: 1.6 }} onFocus={e => (e.target.style.borderColor = T.accent)} onBlur={e => (e.target.style.borderColor = T.border)} />
      <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 10, marginTop: 14 }}>
        {stats.map(s => (
          <div key={s.label} style={{ background: T.card, border: `1.5px solid ${T.border}`, borderRadius: 10, padding: "12px 10px", textAlign: "center" }}>
            <div style={{ fontSize: 20, fontWeight: 800, color: s.color, fontFamily: "Syne, sans-serif", lineHeight: 1.1 }}>{s.value}</div>
            <div style={{ fontSize: 10, color: T.muted, marginTop: 3, fontFamily: "DM Sans, sans-serif" }}>{s.label}</div>
          </div>
        ))}
      </div>
      {text.length > 0 && (
        <button onClick={() => setText("")} style={{ marginTop: 10, padding: "7px 16px", background: "transparent", border: `1px solid ${T.border}`, borderRadius: 8, cursor: "pointer", fontSize: 12, color: T.muted, fontFamily: "DM Sans, sans-serif" }}>Clear</button>
      )}
    </div>
  );
}

export function BMICalculator() {
  const [unit, setUnit] = useState("metric");
  const [height, setHeight] = useState("");
  const [weight, setWeight] = useState("");
  const [heightFt, setHeightFt] = useState("");
  const [heightIn, setHeightIn] = useState("");
  const [bmi, setBmi] = useState(null);
  const getCategory = (b) => {
    if (b < 18.5) return { label: "Underweight", color: T.blue, bg: T.blueDim };
    if (b < 25)   return { label: "Healthy Weight", color: T.green, bg: T.greenDim };
    if (b < 30)   return { label: "Overweight", color: T.gold, bg: T.goldDim };
    return           { label: "Obese", color: "#dc2626", bg: "#fee2e2" };
  };
  const calculate = () => {
    let val;
    if (unit === "metric") {
      const h = parseFloat(height) / 100; const w = parseFloat(weight);
      if (!h || !w || h <= 0 || w <= 0) return;
      val = w / (h * h);
    } else {
      const inches = parseFloat(heightFt) * 12 + parseFloat(heightIn || 0); const w = parseFloat(weight);
      if (!inches || !w) return;
      val = (w / (inches * inches)) * 703;
    }
    setBmi(Math.round(val * 10) / 10);
  };
  const cat = bmi ? getCategory(bmi) : null;
  const iStyle = { ...inputStyle, fontSize: 14, padding: "10px 12px" };
  return (
    <div>
      <div style={{ display: "flex", background: T.bg, borderRadius: 10, padding: 3, marginBottom: 18, width: "fit-content" }}>
        {["metric","imperial"].map(u => (
          <button key={u} onClick={() => { setUnit(u); setBmi(null); }} style={{ padding: "7px 18px", borderRadius: 8, border: "none", cursor: "pointer", fontFamily: "DM Sans, sans-serif", fontSize: 12, fontWeight: 600, background: unit === u ? T.accent : "transparent", color: unit === u ? "white" : T.muted, transition: "all 0.15s" }}>
            {u === "metric" ? "Metric (kg/cm)" : "Imperial (lb/ft)"}
          </button>
        ))}
      </div>
      {unit === "metric" ? (
        <>
          <Row label="Height (cm)"><input type="number" placeholder="e.g. 175" value={height} onChange={e => setHeight(e.target.value)} style={iStyle} /></Row>
          <Row label="Weight (kg)"><input type="number" placeholder="e.g. 70" value={weight} onChange={e => setWeight(e.target.value)} style={iStyle} /></Row>
        </>
      ) : (
        <>
          <Row label="Height"><div style={{ display: "flex", gap: 8 }}><input type="number" placeholder="ft" value={heightFt} onChange={e => setHeightFt(e.target.value)} style={{ ...iStyle, flex: 1 }} /><input type="number" placeholder="in" value={heightIn} onChange={e => setHeightIn(e.target.value)} style={{ ...iStyle, flex: 1 }} /></div></Row>
          <Row label="Weight (lbs)"><input type="number" placeholder="e.g. 154" value={weight} onChange={e => setWeight(e.target.value)} style={iStyle} /></Row>
        </>
      )}
      <button onClick={calculate} style={{ width: "100%", marginTop: 6, padding: "12px 0", background: T.accent, color: "white", border: "none", borderRadius: 10, fontSize: 14, fontWeight: 700, fontFamily: "Syne, sans-serif", cursor: "pointer" }}>Calculate BMI</button>
      {bmi && cat && (
        <div className="tf-bmi-result" style={{ marginTop: 20, background: cat.bg, border: `1.5px solid ${cat.color}44`, borderRadius: 12, padding: 20, textAlign: "center" }}>
          <div style={{ fontSize: 48, fontWeight: 800, color: cat.color, fontFamily: "Syne, sans-serif", lineHeight: 1 }}>{bmi}</div>
          <div style={{ fontSize: 16, fontWeight: 700, color: cat.color, marginTop: 6, fontFamily: "Syne, sans-serif" }}>{cat.label}</div>
          <div style={{ display: "flex", borderRadius: 6, overflow: "hidden", height: 8, marginTop: 16, marginBottom: 4 }}>
            {[{ c: "#93c5fd", w: 25 }, { c: "#4ade80", w: 33 }, { c: "#fbbf24", w: 25 }, { c: "#f87171", w: 17 }].map((s, i) => (
              <div key={i} style={{ flex: s.w, background: s.c }} />
            ))}
          </div>
          <div style={{ display: "flex", justifyContent: "space-between", fontSize: 10, color: T.muted, fontFamily: "DM Sans, sans-serif" }}>
            <span>Under</span><span>Healthy</span><span>Over</span><span>Obese</span>
          </div>
          <div style={{ fontSize: 11, color: T.muted, marginTop: 12, fontFamily: "DM Sans, sans-serif" }}>BMI is a screening tool, not a medical diagnosis.</div>
        </div>
      )}
    </div>
  );
}

export function QRGenerator() {
  const [input, setInput] = useState("");
  const [qrUrl, setQrUrl] = useState("");
  const [size, setSize] = useState(256);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const generate = async () => {
    if (!input.trim()) return;
    setLoading(true); setError("");
    try {
      const url = await QRCodeLib.toDataURL(input.trim(), {
        width: size, margin: 2,
        color: { dark: "#0f0f0d", light: "#ffffff" },
        errorCorrectionLevel: "M",
      });
      setQrUrl(url);
    } catch { setError("Failed to generate. Please try again."); }
    setLoading(false);
  };

  const download = () => {
    const a = document.createElement("a");
    a.download = "qrcode.png"; a.href = qrUrl; a.click();
  };

  return (
    <div>
      <Row label="URL or Text">
        <input type="text" placeholder="https://yoursite.com or any text…" value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => e.key === "Enter" && generate()} style={{ ...inputStyle, fontSize: 14, padding: "10px 12px" }} onFocus={e => (e.target.style.borderColor = T.accent)} onBlur={e => (e.target.style.borderColor = T.border)} />
      </Row>
      <Row label="Size">
        <div style={{ display: "flex", gap: 8 }}>
          {[{ label: "Small", val: 128 }, { label: "Medium", val: 256 }, { label: "Large", val: 512 }].map(s => (
            <button key={s.val} onClick={() => setSize(s.val)} style={{ flex: 1, padding: "7px 0", border: `1.5px solid ${size === s.val ? T.teal : T.border}`, borderRadius: 8, cursor: "pointer", fontFamily: "DM Sans, sans-serif", fontSize: 12, fontWeight: size === s.val ? 700 : 400, background: size === s.val ? T.tealDim : "white", color: size === s.val ? T.teal : T.muted, transition: "all 0.15s" }}>
              {s.label}
            </button>
          ))}
        </div>
      </Row>
      <button onClick={generate} disabled={!input.trim() || loading} style={{ width: "100%", marginTop: 4, padding: "12px 0", background: input.trim() ? T.accent : T.border, color: "white", border: "none", borderRadius: 10, fontSize: 14, fontWeight: 700, fontFamily: "Syne, sans-serif", cursor: input.trim() ? "pointer" : "not-allowed", transition: "background 0.2s" }}>
        {loading ? "Generating…" : "Generate QR Code"}
      </button>
      {error && <div style={{ marginTop: 10, padding: "9px 12px", background: "#fef2f2", border: "1px solid #fecaca", borderRadius: 8, color: "#dc2626", fontSize: 13, fontFamily: "DM Sans, sans-serif" }}>{error}</div>}
      {qrUrl && (
        <div style={{ marginTop: 20, display: "flex", flexDirection: "column", alignItems: "center", gap: 14, padding: 20, background: T.card, border: `1px solid ${T.border}`, borderRadius: 12 }}>
          <img src={qrUrl} alt="QR Code" style={{ borderRadius: 8, boxShadow: "0 2px 16px #0f0f0d14", maxWidth: "100%" }} />
          <button onClick={download} style={{ padding: "9px 24px", background: T.ink, color: "white", border: "none", borderRadius: 8, fontSize: 13, fontWeight: 600, fontFamily: "DM Sans, sans-serif", cursor: "pointer" }}>⬇️ Download PNG</button>
        </div>
      )}
    </div>
  );
}
